language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.6.6
  - 1.7.2

otp_release:
  - 20.3
  - 21.0

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
